[phases.setup]
nixpkgsArchive = "03b825582b09abe3a73b58233e3c8659ad03ff51"

[phases.install]
cmds = ["npm ci --include=dev"]

[phases.build]
cmds = ["npm run deploy:build"]

[start]
cmd = "npm run start:prod"

[variables]
NIXPACKS_NODE_VERSION = "20"
